### ISSUE TITLE
core.datastructures.sentence.java is buggy

### ISSUE THREAD

**Issue by mssammon** [CogComp/cogcomp-nlp#398]
Problem: inherits from TextAnnotation, so has 'views' member.
Some getView() getTopKView() methods call super() so get the parent's view.  Instead, everything should access Sentence's own TextAnnotation field. 
Maybe Sentence should not inherit from TextAnnotation?

**Comment by cowchipkid** [comment]
Why does a sentence subclasses TestAnnotation? Why is Sentence not just a component of a Sentences view?

**Comment by mssammon** [comment]
This probably dates back to inception of whole set of data structure, and back then presumably There Were Reasons.  We can apply a bandaid -- refer to the member TextAnnotation not super() -- or we can try to refactor.  In theory we don't need Sentence, but I'm guessing it will be somewhat painful to actually remove it and replace it with use of sentence View/Constituents. We could try severing the inheritance relation with TextAnnotation instead.

**Comment by bhargav** [comment]
The `Sentence` class implements `AbstractTextAnnotation` which provides most of the TextAnnotation functionality - adding views, getting tokens, constituents.

ViewNames.Sentence has one Constituent for each sentence in the actual text. The `Sentence` class seems to provide a TA-like structure but only restricted to the Sentence's bounds. The `getView` methods create a restricted version of the original TA's view. It keeps the parent TextAnnotation as a protected member so that it can access all the views without creating a copy.

**Comment by cowchipkid** [comment]
Ya, I suspect there was a reason. I have no idea what it was, and doubt we will ever find out. I reaffirm my believe that simplicity is beauty in code, and I think the `Sentence` breaks the paradigm, and confuses an otherwise elegant design. Furthermore, there are sentence views, and there are `Sentence` objects. Confusing? You bet. Do we ever subclass `Constituent`? Maybe `Sentence` is a subclass of `Constituent`? Just as a subtle hint, if you need somebody to work on this, I would relish working on the core datastructures compared to working on coref, if you could just convince Dan of the same...

**Comment by mssammon** [comment]
@cowchipkid looks like you and @bhargav posted around the same time.  @bhargav the problem is that if you remove a view from a TextAnnotation, its Sentences' parent TA does not get updated.

**Comment by bhargav** [comment]
Removing a view from parent TA is reflected in the Sentence. But removing views from Sentences are not supported (propagated back to the parent TA). Because Sentence is used in feature extraction and other downstream places, I suggest throwing an `UnsupportedOperationException` for methods in Sentence class that might be troublesome (especially all the methods that try to edit a TA).
