### ISSUE TITLE
How to get sentences? 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/cogcomp-nlp#473]
How would you get the raw string of each sentence? (other than filtering constituents according to their sentence number and concatenating their surface string). 

Tried this: 
```
        TextAnnotation ta = DummyTextAnnotationGenerator.generateAnnotatedTextAnnotation(false, 3);
        System.out.println(ta.getSentence(0).text);
        System.out.println(ta.getSentence(1).text);
        System.out.println(ta.getSentence(2).text);
```

This gives me: 
```
null
null
null
```

**Comment by cogcomp-dev** [comment]
Can you use the sentence *view* constituents instead?

**Comment by danyaljj** [comment]
In what scenarios is this view constructed? 
Like I don't see it in the output of pipeline: 
http://austen.cs.illinois.edu:8080/annotate?text=%22This%20is%20a%20sample%20sentence.%20I%27m%20happy.%22&views=POS

**Comment by mssammon** [comment]
I'm pretty sure that at one point it was the default behavior of TokenizerTextAnnotationBuilder. Now I see that one method instantiates it, but another doesn't.  I'm inclined to set/restore this as the default behavior.  Any objections?

**Comment by bhargav** [comment]
In the [TextAnnotation](https://github.com/CogComp/cogcomp-nlp/blob/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/core/datastructures/textannotation/TextAnnotation.java#L91) constructor the SENTENCE view is always added based on sentenceEndPositions. So the view should always be present. But the `protected List<Sentence> sentences` field is not populated unless setSentence is called.

@danyaljj For the behavior you see in the Pipeline Webserver, the serialization logic does not serialize the sentence view. Only sentence end position offsets are serialized. The `ViewNames.SENTENCE` view is recreated upon deserialization.

**Comment by danyaljj** [comment]
Ah you're right @bhargav. Verified it and it indeed contains the SENTENCE view in the deserialization.

**Comment by bhargav** [comment]
I realized my comment wasn't very clear. To summarize:
- `textAnnotation.getView(ViewNames.SENTENCE):` Should always work and return a SpanLabelView as the view is created in a TextAnnotation constructor. The View is not serialized to JSON/Protobuf instead only sentenceEndPosition and score fields are serialized.
- `textAnnotation.getSentence(int sentenceId):` Returns a read-only restricted `Sentence` object that contains all views restricted to the sentence level.

Since Sentence class already implements `AbstractTextAnnotation`, we can implement the `getText()` and related methods to fix this.

**Comment by danyaljj** [comment]
@bhargav was right. Closing this.
